const world=document.getElementById('world');
const actors=document.getElementById('actors');
const ctx=world.getContext('2d');
const img={};
const FARMERS=[{id:'Bernard',json:'Bernard.json',atlas:'Bernard.atlas.txt',png:'Bernard.png',scale:0.28},{id:'Daisy',json:'Daisy.json',atlas:'Daisy.atlas.txt',png:'Daisy.png',scale:0.28},{id:'Kael',json:'Kael.json',atlas:'Kael.atlas.txt',png:'Kael.png',scale:0.26},{id:'Leofric',json:'Leofric.json',atlas:'Leofric.atlas.txt',png:'Leofric.png',scale:0.26},{id:'Martin',json:'Martin.json',atlas:'Martin.atlas.txt',png:'Martin.png',scale:0.26},{id:'Noah',json:'Noah.json',atlas:'Noah.atlas.txt',png:'Noah.png',scale:0.26},{id:'Otis',json:'Otis.json',atlas:'Otis.atlas.txt',png:'Otis.png',scale:0.26},{id:'Draven',json:'Draven.json',atlas:'Draven.atlas.txt',png:'Draven.png',scale:0.26},{id:'Reaper',json:'Crimson Reaper.json',atlas:'Crimson Reaper.atlas.txt',png:'Crimson Reaper.png',scale:0.24},{id:'Skullfang',json:'Skullfang.json',atlas:'Skullfang.atlas.txt',png:'Skullfang.png',scale:0.24}];
const STOCK=[{k:'chicken',json:'Chicken.json',atlas:'Chicken.atlas.txt',png:'iso_chicken.png',alt:'chicken.png',scale:0.18,w:44,h:44},{k:'cow',json:'Cow.json',atlas:'Cow.atlas.txt',png:'iso_cow.png',alt:'cow.png',scale:0.2,w:70,h:54},{k:'sheep',json:'Sheep.json',atlas:'Sheep.atlas.txt',png:'iso_sheep.png',alt:'sheep.png',scale:0.2,w:56,h:50},{k:'goat',json:'Goat.json',atlas:'Goat.atlas.txt',png:'iso_sheep.png',alt:'sheep.png',scale:0.2,w:54,h:50},{k:'pig',json:'Pig.json',atlas:'Pig.atlas.txt',png:'iso_cow.png',alt:'cow.png',scale:0.2,w:58,h:48}];
const SPRITE_PNG=['iso_chicken.png','iso_cow.png','iso_sheep.png','chicken.png','cow.png','sheep.png','fox.png','rabbit.png','wolf.png'];
const PNG=['Water.png','Grassy Island.png','Empty Soil.png','1.png','4.png','8.png','Big Tree_01.png','Stump.png','Horizontal Wooden Bridge.png','Wooden Pier.png','Wheat_Seed.png','Wheat.png','Wheat_02.png','Wheat_03.png','Tomato_Seed.png','Tomato.png','Tomato_02.png','Tomato_03.png','Corn Seed_01.png','Corn.png','Corn_02.png','Corn_03.png','Carrot.png','Carrot_01.png','Carrot_02.png','Carrot_03.png'].concat(SPRITE_PNG).concat(FARMERS.map(f=>f.png));
const CROPS={wheat:['Wheat_Seed.png','Wheat.png','Wheat_02.png','Wheat_03.png'],tomato:['Tomato_Seed.png','Tomato.png','Tomato_02.png','Tomato_03.png'],corn:['Corn Seed_01.png','Corn.png','Corn_02.png','Corn_03.png'],carrot:['Carrot.png','Carrot_01.png','Carrot_02.png','Carrot_03.png']};
const GRASS={x0:620,x1:820,y0:360,y1:530};
const PRICE={wheat:8,tomato:10,corn:9,carrot:8,wood:6,fish:12,meat:15};
const FARM_TOOLS=[['wheat','Wheat',0],['tomato','Tomato',0],['corn','Corn',0],['carrot','Carrot',0],['harvest','Harvest',0],['chop','Chop',0],['sell','Sell',0],['expand','Clear 80PT',1]];
const ACT_TOOLS=[['fish','Fish Lv1',1],['hunt','Hunt Lv5',5],['tame','Tame Lv20',20],['chickens','Chickens Lv10',10],['cattle','Cattle Lv15',15]];
const state={screen:'select',farmer:'Bernard',lv:1,xp:0,pt:800,tool:'wheat',sheet:null,keys:{},cam:{x:40,y:10},time:0,last:0,msg:'',msgT:0,openedFish:false,openedHunt:false,openedLive:false,openedCattle:false,openedTame:false,player:{x:430,y:390,facing:1},target:null,plots:[],trees:[],animals:[],wild:[],guards:[],inv:{wheat:2,tomato:2,corn:1,carrot:1,wood:0,fish:0,meat:0,caught:0}};
let spineOk=false,scene=null,assetMgr=null;const skeletons={};const templates={};
function say(t){state.msg=t;state.msgT=3;}
function knockWhite(src){try{const c=document.createElement('canvas');c.width=src.naturalWidth;c.height=src.naturalHeight;const g=c.getContext('2d');g.drawImage(src,0,0);const id=g.getImageData(0,0,c.width,c.height);const d=id.data;for(let i=0;i<d.length;i+=4){if(d[i]>242&&d[i+1]>242&&d[i+2]>242)d[i+3]=0;}g.putImageData(id,0,0);return c;}catch(e){return src;}}
function loadPng(name){return new Promise(res=>{const i=new Image();i.onload=()=>{img[name]=SPRITE_PNG.indexOf(name)>=0?knockWhite(i):i;res(img[name]);};i.onerror=()=>{img[name]=i;res(i);};i.src=encodeURI(name);});}
function ready(name){const i=img[name];return i&&((i.naturalWidth||i.width)>0);}
function pickSprite(spec){if(spec&&ready(spec.png))return spec.png;if(spec&&spec.alt&&ready(spec.alt))return spec.alt;return '';}
function drawSpr(name,x,y,w,h,flip){if(!name||!ready(name))return;const dx=x-state.cam.x,dy=y-state.cam.y;if(!flip){ctx.drawImage(img[name],dx,dy,w,h);return;}ctx.save();ctx.translate(dx+w/2,dy);ctx.scale(-1,1);ctx.drawImage(img[name],-w/2,0,w,h);ctx.restore();}
function clampGrass(o){if(o.x<GRASS.x0){o.x=GRASS.x0;o.dx=Math.abs(o.dx||0.2);}if(o.x>GRASS.x1){o.x=GRASS.x1;o.dx=-Math.abs(o.dx||0.2);}if(o.y<GRASS.y0){o.y=GRASS.y0;o.dy=Math.abs(o.dy||0.2);}if(o.y>GRASS.y1){o.y=GRASS.y1;o.dy=-Math.abs(o.dy||0.2);}}
function pickAnim(data,names){for(const n of names){if(data.findAnimation(n))return n;}const all=data.animations||[];return all[0]?all[0].name:null;}
function setAnim(id,prefer,loop){const s=skeletons[id];if(!s)return;const name=pickAnim(s.data,prefer);if(!name||s.last===name)return;s.anim.setAnimation(0,name,loop);s.last=name;}
function makeActor(id,data){const skeleton=new spine.Skeleton(data);const anim=new spine.AnimationState(new spine.AnimationStateData(data));anim.data.defaultMix=0.12;skeleton.setToSetupPose();skeletons[id]={skeleton,anim,data,last:''};}
function cloneStock(kind,x,y){const a={k:kind,x:Math.min(GRASS.x1,Math.max(GRASS.x0,x)),y:Math.min(GRASS.y1,Math.max(GRASS.y0,y)),dx:0.2,dy:0.1};state.animals.push(a);}
function makeWorld(){state.plots=[];for(let r=0;r<4;r++)for(let c=0;c<5;c++)state.plots.push({x:380+c*54,y:330+r*48,locked:!(c<3&&r<2),crop:'',stage:0,grow:0});state.trees=[{x:240,y:200,hp:3},{x:300,y:180,hp:3},{x:800,y:190,hp:3},{x:860,y:230,hp:3}];state.animals=[{k:'chicken',x:680,y:430,dx:0.35,dy:0.08},{k:'chicken',x:740,y:470,dx:-0.25,dy:0.12},{k:'cow',x:780,y:450,dx:0.12,dy:0},{k:'sheep',x:700,y:500,dx:-0.18,dy:0.06}];state.wild=[];respawnWild(true);state.guards=[];}
function respawnWild(force){if(!force&&state.wild.filter(w=>w.alive).length>=4)return;const kinds=['fox','rabbit','wolf'];while(state.wild.filter(w=>w.alive).length<4){const k=kinds[Math.floor(Math.random()*kinds.length)];state.wild.push({k,x:640+Math.random()*160,y:380+Math.random()*120,dx:Math.random()-0.5,dy:Math.random()-0.5,alive:true});}}
function farmerMeta(){return FARMERS.find(f=>f.id===state.farmer)||FARMERS[0];}
function initSpine(){if(typeof spine==='undefined')return Promise.resolve(false);try{const gl=actors.getContext('webgl',{alpha:true,premultipliedAlpha:true});if(!gl)return Promise.resolve(false);scene=new spine.SceneRenderer(actors,gl);assetMgr=new spine.AssetManager(gl,'');FARMERS.forEach(f=>{assetMgr.loadJson(f.json);assetMgr.loadTextureAtlas(f.atlas);});return new Promise(res=>{const wait=()=>{if(!assetMgr.isLoadingComplete()){requestAnimationFrame(wait);return;}try{FARMERS.forEach(f=>{const atlas=assetMgr.require(f.atlas);const json=assetMgr.require(f.json);const reader=new spine.SkeletonJson(new spine.AtlasAttachmentLoader(atlas));reader.scale=f.scale;templates[f.id]=reader.readSkeletonData(json);makeActor(f.id,templates[f.id]);});spineOk=true;res(true);}catch(err){console.warn(err);res(false);}};wait();});}catch(e){return Promise.resolve(false);}}
function blit(id,x,y,facing,dt,idleNames,walkNames,moving){const s=skeletons[id];if(!s)return false;setAnim(id,moving?walkNames:idleNames,true);s.anim.update(dt);s.anim.apply(s.skeleton);s.skeleton.x=x;s.skeleton.y=-y;s.skeleton.scaleX=Math.abs(s.skeleton.scaleX||1)*(facing<0?-1:1);try{if(spine.Physics)s.skeleton.updateWorldTransform(spine.Physics.update);else s.skeleton.updateWorldTransform();}catch(e){try{s.skeleton.updateWorldTransform();}catch(e2){}}scene.drawSkeleton(s.skeleton,true);return true;}
function drawActors(dt,moving){if(!spineOk||!scene)return;scene.camera.position.x=state.cam.x+actors.width/2;scene.camera.position.y=-(state.cam.y+actors.height/2);scene.camera.viewportWidth=actors.width;scene.camera.viewportHeight=actors.height;scene.begin();blit(state.farmer,state.player.x,state.player.y,state.player.facing,dt,['idle_Simple','Idle','idle','Happy'],['walk','Walk','run','Run'],moving);scene.end();}
function drawStock(a){const spec=STOCK.find(s=>s.k===a.k);const file=pickSprite(spec);if(!file)return;const bob=Math.abs(Math.sin(state.time*8+a.x))*2;drawSpr(file,a.x,a.y-bob,spec.w,spec.h,a.dx<0);}
function drawWorld(){ctx.clearRect(0,0,world.width,world.height);ctx.fillStyle='#1b6b9a';ctx.fillRect(0,0,world.width,world.height);for(let y=-1;y<8;y++)for(let x=-1;x<8;x++)drawSpr('Water.png',x*220,y*180,240,200);drawSpr('Grassy Island.png',80,20,980,700);drawSpr('1.png',160,90,220,200);drawSpr('4.png',820,80,200,180);drawSpr('8.png',300,100,160,150);drawSpr('Horizontal Wooden Bridge.png',40,330,160,70);drawSpr('Wooden Pier.png',900,330,160,80);state.trees.forEach(t=>{if(t.hp<=0)drawSpr('Stump.png',t.x,t.y+40,70,50);else drawSpr('Big Tree_01.png',t.x,t.y,100,140);});state.plots.forEach(p=>{const dx=p.x-state.cam.x,dy=p.y-state.cam.y;if(p.locked){ctx.fillStyle='rgba(20,30,10,.45)';ctx.fillRect(dx,dy,50,44);ctx.fillStyle='#fff';ctx.font='11px sans-serif';ctx.fillText('WILD',dx+8,dy+26);return;}drawSpr('Empty Soil.png',p.x,p.y,50,44);if(p.crop){const st=CROPS[p.crop];drawSpr(st[Math.min(p.stage,st.length-1)],p.x+8,p.y-6,34,42);}});state.wild.forEach(w=>{if(w.alive)drawSpr(w.k+'.png',w.x,w.y,42,36,w.dx<0);});state.guards.forEach(g=>drawSpr(g.spr,g.x,g.y,40,36));state.animals.forEach(drawStock);if(!spineOk){const f=farmerMeta();drawSpr(f.png,state.player.x-28,state.player.y-70,56,80,state.player.facing<0);}}
function nightTint(){const t=(Math.sin(state.time/18)+1)/2;if(t>0.55){ctx.fillStyle='rgba(8,12,40,'+((t-0.55)/0.45)*0.38+')';ctx.fillRect(0,0,world.width,world.height);}}
function fitCam(){state.cam.x=Math.max(0,Math.min(1140-world.width,state.player.x-world.width/2));state.cam.y=Math.max(0,Math.min(760-world.height,state.player.y-world.height/2));if(world.width>=1100){state.cam.x=20;state.cam.y=0;}}
function updateLogic(dt){const p=state.player;let vx=(state.keys.ArrowRight||state.keys.d||state.keys.D?1:0)-(state.keys.ArrowLeft||state.keys.a||state.keys.A?1:0);let vy=(state.keys.ArrowDown||state.keys.s||state.keys.S?1:0)-(state.keys.ArrowUp||state.keys.w||state.keys.W?1:0);if(state.target){const dx=state.target.x-p.x,dy=state.target.y-p.y,dist=Math.hypot(dx,dy);if(dist<8)state.target=null;else{vx=dx/dist;vy=dy/dist;}}const moving=Math.abs(vx)+Math.abs(vy)>0;if(moving){const len=Math.hypot(vx,vy)||1;p.x+=(vx/len)*140*dt;p.y+=(vy/len)*140*dt;if(vx!==0)p.facing=vx<0?-1:1;}p.x=Math.max(260,Math.min(820,p.x));p.y=Math.max(280,Math.min(540,p.y));fitCam();state.animals.forEach(a=>{if(Math.random()<0.01){a.dx=(Math.random()-0.5)*0.8;a.dy=(Math.random()-0.5)*0.8;}a.x+=a.dx*40*dt;a.y+=a.dy*40*dt;clampGrass(a);});state.wild.forEach(w=>{if(!w.alive)return;if(Math.random()<0.015){w.dx=(Math.random()-0.5)*0.9;w.dy=(Math.random()-0.5)*0.9;}w.x+=w.dx*40*dt;w.y+=w.dy*40*dt;clampGrass(w);});state.guards.forEach((g,i)=>{g.x=p.x+Math.cos(state.time*0.8+i)*40-16;g.y=p.y+Math.sin(state.time*0.8+i)*24;});state.plots.forEach(pl=>{if(pl.crop&&pl.stage<CROPS[pl.crop].length-1){pl.grow+=dt;if(pl.grow>5){pl.grow=0;pl.stage+=1;}}});if(state.msgT>0)state.msgT-=dt;if(Math.random()<0.003)respawnWild(false);return moving;}
function hud(){document.getElementById('stats').innerHTML='PAWLY · '+state.farmer+' · Lv '+state.lv+' · '+Math.min(state.xp,100)+'/100 · '+state.pt+' PT<br>W/T/C/R '+state.inv.wheat+'/'+state.inv.tomato+'/'+state.inv.corn+'/'+state.inv.carrot+' · Wood '+state.inv.wood+' Fish '+state.inv.fish+' Meat '+state.inv.meat+(state.msgT>0?'<br>'+state.msg:'');}
function renderSheet(){const sheet=document.getElementById('sheet');if(!state.sheet){sheet.classList.add('hidden');sheet.innerHTML='';return;}sheet.classList.remove('hidden');sheet.innerHTML='';(state.sheet==='farm'?FARM_TOOLS:ACT_TOOLS).forEach(([id,label,lv])=>{const b=document.createElement('button');b.textContent=state.lv>=lv?label:label+' 🔒';if(state.tool===id)b.classList.add('on');b.onclick=()=>{if(state.lv<lv){say('Need level '+lv);return;}state.tool=id;renderSheet();if(id==='sell')sellAll();};sheet.appendChild(b);});}
function canUse(id,lv,cost,flag){if(state.lv<lv){say('Need level '+lv);return false;}if(flag&&!state[flag]){if(state.pt<cost){say('Need '+cost+' PT');return false;}state.pt-=cost;state[flag]=true;save();say('Unlocked '+id+' (-'+cost+' PT)');}return true;}
function addXp(n){state.xp+=n;while(state.xp>=100&&state.lv<99){const fee=state.lv<5?50:state.lv<15?100:state.lv<30?180:360;if(state.pt<fee){state.xp=100;say('Need '+fee+' PT to level');break;}state.pt-=fee;state.xp-=100;state.lv+=1;say('Level '+state.lv);}save();}
function sellAll(){let gained=0;Object.keys(PRICE).forEach(k=>{const n=state.inv[k]||0;if(!n)return;gained+=n*PRICE[k];state.inv[k]=0;});if(!gained){say('Nothing to sell');return;}state.pt+=gained;say('Sold for '+gained+' PT');save();}
function worldPos(ev,el){const r=el.getBoundingClientRect();return{x:((ev.clientX-r.left)/r.width)*world.width+state.cam.x,y:((ev.clientY-r.top)/r.height)*world.height+state.cam.y};}
function hitWild(pos){return state.wild.find(w=>w.alive&&pos.x>=w.x&&pos.x<w.x+48&&pos.y>=w.y&&pos.y<w.y+40);}
function save(){try{localStorage.setItem('pawly-estate-v4',JSON.stringify({farmer:state.farmer,lv:state.lv,xp:state.xp,pt:state.pt,inv:state.inv,openedFish:state.openedFish,openedHunt:state.openedHunt,openedLive:state.openedLive,openedCattle:state.openedCattle,openedTame:state.openedTame}));}catch(e){}}
function load(){try{const raw=localStorage.getItem('pawly-estate-v4')||localStorage.getItem('pawly-estate-v3');if(!raw)return;const d=JSON.parse(raw);['farmer','lv','xp','pt','inv','openedFish','openedHunt','openedLive','openedCattle','openedTame'].forEach(k=>{if(d[k]!==undefined)state[k]=d[k];});}catch(e){}}
function onTap(ev){if(state.screen!=='play')return;const pos=worldPos(ev.touches?ev.touches[0]:ev,world);const plot=state.plots.find(p=>pos.x>=p.x&&pos.x<p.x+50&&pos.y>=p.y&&pos.y<p.y+44);const tree=state.trees.find(t=>t.hp>0&&pos.x>=t.x&&pos.x<t.x+110&&pos.y>=t.y&&pos.y<t.y+150);const prey=hitWild(pos);if(state.tool==='fish'){if(!canUse('fish',1,100,'openedFish'))return;if(pos.x>880&&pos.y>300&&pos.y<460){state.inv.fish+=1;addXp(3);say('Caught a fish');}return;}if(state.tool==='hunt'){if(!canUse('hunt',5,150,'openedHunt'))return;if(prey){prey.alive=false;state.inv.meat+=1;state.inv.caught+=1;addXp(8);say('Hunted '+prey.k);respawnWild(false);}else say('Tap a fox / rabbit / wolf');return;}if(state.tool==='tame'){if(!canUse('tame',20,300,'openedTame'))return;if(state.inv.caught<1){say('Hunt first');return;}if(prey&&prey.alive){prey.alive=false;state.inv.caught-=1;state.guards.push({spr:prey.k+'.png',x:prey.x,y:prey.y});addXp(10);say(prey.k+' now guards');}else say('Tap a live wild animal');return;}if(state.tool==='chickens'){if(!canUse('live',10,200,'openedLive'))return;cloneStock('chicken',pos.x,pos.y);addXp(4);say('Added chickens');return;}if(state.tool==='cattle'){if(!canUse('cattle',15,250,'openedCattle'))return;cloneStock(Math.random()<0.5?'cow':'sheep',pos.x,pos.y);addXp(5);say('Added cattle');return;}if(state.tool==='chop'&&tree){tree.hp-=1;if(tree.hp<=0){state.inv.wood+=2;addXp(6);say('Tree down');}return;}if(plot){if(plot.locked){if(state.tool==='expand'&&state.pt>=80){state.pt-=80;plot.locked=false;addXp(2);save();}else say('Open Farm → Clear 80PT');return;}if(state.tool==='harvest'){const st=CROPS[plot.crop];if(plot.crop&&st&&plot.stage>=st.length-1){state.inv[plot.crop]+=1;addXp(4);plot.crop='';plot.stage=0;plot.grow=0;}return;}if(CROPS[state.tool]&&!plot.crop){plot.crop=state.tool;plot.stage=0;plot.grow=0;return;}}state.target=pos;}
function loop(ts){const dt=Math.min(0.05,(ts-(state.last||ts))/1000);state.last=ts;state.time+=dt;if(state.screen==='play'){const moving=updateLogic(dt);drawWorld();nightTint();drawActors(dt,moving);hud();}requestAnimationFrame(loop);}
function fit(){world.width=actors.width=Math.min(1280,window.innerWidth);world.height=actors.height=Math.min(720,window.innerHeight);fitCam();}
function fillFaces(){const box=document.getElementById('faces');box.innerHTML='';FARMERS.forEach(f=>{const b=document.createElement('button');const im=document.createElement('img');im.src=encodeURI(f.png);im.alt=f.id;const s=document.createElement('span');s.textContent=f.id;b.appendChild(im);b.appendChild(s);b.onclick=()=>{state.farmer=f.id;save();document.getElementById('select').style.display='none';state.screen='play';};box.appendChild(b);});}
document.getElementById('btnFarm').onclick=()=>{state.sheet=state.sheet==='farm'?null:'farm';renderSheet();};
document.getElementById('btnAct').onclick=()=>{state.sheet=state.sheet==='act'?null:'act';renderSheet();};
window.addEventListener('resize',fit);window.addEventListener('keydown',e=>state.keys[e.key]=true);window.addEventListener('keyup',e=>state.keys[e.key]=false);
world.addEventListener('click',onTap);world.addEventListener('touchstart',e=>{onTap(e);e.preventDefault();},{passive:false});
load();fit();makeWorld();fillFaces();
Promise.all(PNG.map(loadPng)).then(()=>initSpine()).finally(()=>{const boot=document.getElementById('boot');if(boot)boot.style.display='none';requestAnimationFrame(loop);});
