const world=document.getElementById('world');const actors=document.getElementById('actors');const ctx=world.getContext('2d');
const img={};
const PNG=['Water.png','Grassy Island.png','Empty Soil.png','1.png','4.png','8.png','Big Tree_01.png','Stump.png','Horizontal Wooden Bridge.png','Wooden Pier.png','Wheat_Seed.png','Wheat.png','Wheat_02.png','Wheat_03.png','Tomato_Seed.png','Tomato.png','Tomato_02.png','Tomato_03.png','Corn Seed_01.png','Corn.png','Corn_02.png','Corn_03.png','Carrot.png','Carrot_01.png','Carrot_02.png','Carrot_03.png','fox.png','rabbit.png','wolf.png','Fish.png'];
const CROPS={wheat:['Wheat_Seed.png','Wheat.png','Wheat_02.png','Wheat_03.png'],tomato:['Tomato_Seed.png','Tomato.png','Tomato_02.png','Tomato_03.png'],corn:['Corn Seed_01.png','Corn.png','Corn_02.png','Corn_03.png'],carrot:['Carrot.png','Carrot_01.png','Carrot_02.png','Carrot_03.png']};
const SPINE_KIND={boy:{json:'Bernard.json',atlas:'Bernard.atlas.txt',scale:0.34,idle:'idle_Simple',walk:'walk'},girl:{json:'Daisy.json',atlas:'Daisy.atlas.txt',scale:0.34,idle:'idle_Simple',walk:'walk'},chicken:{json:'Chicken.json',atlas:'Chicken.atlas.txt',scale:0.2,idle:'Idle',walk:'Idle'},cow:{json:'Cow.json',atlas:'Cow.atlas.txt',scale:0.22,idle:'Idle',walk:'Walk'},sheep:{json:'Sheep.json',atlas:'Sheep.atlas.txt',scale:0.22,idle:'Idle',walk:'Walk'},goat:{json:'Goat.json',atlas:'Goat.atlas.txt',scale:0.22,idle:'Idle',walk:'Walk'},pig:{json:'Pig.json',atlas:'Pig.atlas.txt',scale:0.22,idle:'Idle',walk:'Walk'}};
const GRASS={x0:260,x1:820,y0:280,y1:540};
const state={screen:'select',gender:'boy',lv:1,xp:0,pt:800,tool:'wheat',keys:{},cam:{x:40,y:10},time:0,last:0,msg:'',msgT:0,openedFish:false,openedHunt:false,openedLive:false,openedCattle:false,openedTame:false,player:{x:430,y:390,facing:1},target:null,plots:[],trees:[],animals:[],wild:[],guards:[],inv:{wheat:2,tomato:2,corn:1,carrot:1,wood:0,fish:0,meat:0,caught:0}};
let spineOk=false,scene=null,assetMgr=null;const skeletons={};
function say(t){state.msg=t;state.msgT=3;}
function loadPng(name){return new Promise(res=>{const i=new Image();img[name]=i;i.onload=()=>res(i);i.onerror=()=>res(i);i.src=encodeURI(name);});}
function ready(name){const i=img[name];return i&&i.complete&&i.naturalWidth>0;}
function drawSpr(name,x,y,w,h){if(!ready(name))return;ctx.drawImage(img[name],x-state.cam.x,y-state.cam.y,w,h);}
function clampGrass(o){if(o.x<GRASS.x0){o.x=GRASS.x0;o.dx=Math.abs(o.dx||0.2);}if(o.x>GRASS.x1){o.x=GRASS.x1;o.dx=-Math.abs(o.dx||0.2);}if(o.y<GRASS.y0){o.y=GRASS.y0;o.dy=Math.abs(o.dy||0.2);}if(o.y>GRASS.y1){o.y=GRASS.y1;o.dy=-Math.abs(o.dy||0.2);}}
function makeWorld(){state.plots=[];for(let r=0;r<4;r++)for(let c=0;c<5;c++)state.plots.push({x:380+c*54,y:330+r*48,locked:!(c<3&&r<2),crop:'',stage:0,grow:0});state.trees=[{x:240,y:200,hp:3},{x:300,y:180,hp:3},{x:800,y:190,hp:3},{x:860,y:230,hp:3}];state.animals=[{k:'chicken',x:560,y:480,dx:0.3,dy:0.1},{k:'chicken',x:600,y:500,dx:-0.2,dy:0.15}];state.wild=[{k:'fox',x:320,y:500,dx:0.35,dy:0.1,alive:true},{k:'rabbit',x:360,y:520,dx:-0.3,dy:0.08,alive:true},{k:'wolf',x:300,y:470,dx:0.2,dy:-0.1,alive:true},{k:'fox',x:760,y:500,dx:-0.25,dy:0.1,alive:true},{k:'rabbit',x:790,y:520,dx:0.2,dy:-0.12,alive:true}];state.guards=[];}
function spawnStock(kind,x,y){const a={k:kind,x:Math.min(GRASS.x1,Math.max(GRASS.x0,x)),y:Math.min(GRASS.y1,Math.max(GRASS.y0,y)),dx:0.2,dy:0.1};state.animals.push(a);const base=skeletons[kind];if(base){const skeleton=new spine.Skeleton(base.data);const anim=new spine.AnimationState(new spine.AnimationStateData(base.data));const nid=kind+'_'+state.animals.length;a.sid=nid;skeletons[nid]={skeleton,anim,data:base.data,last:''};setAnim(nid,SPINE_KIND[kind].idle,true);}}
function initSpine(){if(typeof spine==='undefined')return Promise.resolve(false);try{const gl=actors.getContext('webgl',{alpha:true,premultipliedAlpha:true});if(!gl)return Promise.resolve(false);scene=new spine.SceneRenderer(actors,gl);assetMgr=new spine.AssetManager(gl,'');Object.values(SPINE_KIND).forEach(k=>{assetMgr.loadJson(k.json);assetMgr.loadTextureAtlas(k.atlas);});return new Promise(res=>{const wait=()=>{if(assetMgr.isLoadingComplete()){try{Object.entries(SPINE_KIND).forEach(([id,k])=>{const atlas=assetMgr.require(k.atlas);const json=assetMgr.require(k.json);const skelJson=new spine.SkeletonJson(new spine.AtlasAttachmentLoader(atlas));skelJson.scale=k.scale;const data=skelJson.readSkeletonData(json);const skeleton=new spine.Skeleton(data);const anim=new spine.AnimationState(new spine.AnimationStateData(data));anim.data.defaultMix=0.15;skeleton.setToSetupPose();skeletons[id]={skeleton,anim,data,last:k.idle};setAnim(id,k.idle,true);});state.animals.forEach((a,i)=>{const base=skeletons[a.k];if(!base)return;const skeleton=new spine.Skeleton(base.data);const anim=new spine.AnimationState(new spine.AnimationStateData(base.data));const nid=a.k+'_'+i;a.sid=nid;skeletons[nid]={skeleton,anim,data:base.data,last:''};setAnim(nid,SPINE_KIND[a.k].idle,true);});spineOk=true;res(true);}catch(err){console.warn(err);res(false);}}else requestAnimationFrame(wait);};wait();});}catch(e){return Promise.resolve(false);}}
function setAnim(id,name,loop){const s=skeletons[id];if(!s||!name||s.last===name)return;if(!s.data.findAnimation(name))return;s.anim.setAnimation(0,name,loop);s.last=name;}
function canUse(id,lv,cost,flag){if(state.lv<lv){say('Need level '+lv);return false;}if(flag&&!state[flag]){if(state.pt<cost){say('Need '+cost+' PT');return false;}state.pt-=cost;state[flag]=true;say('Unlocked '+id+' (-'+cost+' PT)');}return true;}
function drawFarmerMark(){const p=state.player;const x=p.x-state.cam.x,y=p.y-state.cam.y;ctx.save();ctx.translate(x,y);if(p.facing<0)ctx.scale(-1,1);ctx.fillStyle=state.gender==='girl'?'#e8a0c0':'#3d6adf';ctx.fillRect(-10,-36,20,22);ctx.fillStyle='#f2d2b0';ctx.beginPath();ctx.arc(0,-42,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#2a2416';ctx.fillRect(-8,-14,16,14);ctx.fillStyle='#c9a227';ctx.fillRect(-12,-50,24,8);ctx.restore();}
function drawWorld(){ctx.clearRect(0,0,world.width,world.height);ctx.fillStyle='#1b6b9a';ctx.fillRect(0,0,world.width,world.height);for(let y=-1;y<8;y++)for(let x=-1;x<8;x++)drawSpr('Water.png',x*220,y*180,240,200);drawSpr('Grassy Island.png',80,20,980,700);drawSpr('1.png',160,90,220,200);drawSpr('4.png',820,80,200,180);drawSpr('8.png',300,100,160,150);drawSpr('Horizontal Wooden Bridge.png',40,330,160,70);drawSpr('Wooden Pier.png',900,330,160,80);state.trees.forEach(t=>{if(t.hp<=0)drawSpr('Stump.png',t.x,t.y+40,70,50);else drawSpr('Big Tree_01.png',t.x,t.y,100,140);});state.plots.forEach(p=>{const dx=p.x-state.cam.x,dy=p.y-state.cam.y;if(p.locked){ctx.fillStyle='rgba(20,30,10,.45)';ctx.fillRect(dx,dy,50,44);ctx.fillStyle='#fff';ctx.font='11px sans-serif';ctx.fillText('WILD',dx+8,dy+26);return;}drawSpr('Empty Soil.png',p.x,p.y,50,44);if(p.crop){const st=CROPS[p.crop];drawSpr(st[Math.min(p.stage,st.length-1)],p.x+8,p.y-6,34,42);}});state.wild.forEach(w=>{if(w.alive)drawSpr(w.k+'.png',w.x,w.y,42,36);});state.guards.forEach(g=>drawSpr(g.spr,g.x,g.y,40,36));if(!spineOk)drawFarmerMark();}
function nightTint(){const t=(Math.sin(state.time/18)+1)/2;if(t>0.55){ctx.fillStyle='rgba(8,12,40,'+((t-0.55)/0.45)*0.38+')';ctx.fillRect(0,0,world.width,world.height);}}
function fitCam(){state.cam.x=Math.max(0,Math.min(1140-world.width,state.player.x-world.width/2));state.cam.y=Math.max(0,Math.min(760-world.height,state.player.y-world.height/2));if(world.width>=1100){state.cam.x=20;state.cam.y=0;}}
function updateLogic(dt){const p=state.player;let vx=(state.keys.ArrowRight||state.keys.d||state.keys.D?1:0)-(state.keys.ArrowLeft||state.keys.a||state.keys.A?1:0);let vy=(state.keys.ArrowDown||state.keys.s||state.keys.S?1:0)-(state.keys.ArrowUp||state.keys.w||state.keys.W?1:0);if(state.target){const dx=state.target.x-p.x,dy=state.target.y-p.y,dist=Math.hypot(dx,dy);if(dist<8)state.target=null;else{vx=dx/dist;vy=dy/dist;}}const moving=Math.abs(vx)+Math.abs(vy)>0;if(moving){const len=Math.hypot(vx,vy)||1;p.x+=(vx/len)*140*dt;p.y+=(vy/len)*140*dt;if(vx!==0)p.facing=vx<0?-1:1;}p.x=Math.max(GRASS.x0,Math.min(GRASS.x1,p.x));p.y=Math.max(GRASS.y0,Math.min(GRASS.y1,p.y));fitCam();const farmer=state.gender==='girl'?'girl':'boy';setAnim(farmer,moving?SPINE_KIND[farmer].walk:SPINE_KIND[farmer].idle,true);state.animals.forEach(a=>{if(Math.random()<0.008){a.dx=(Math.random()-0.5)*0.7;a.dy=(Math.random()-0.5)*0.7;}a.x+=a.dx*36*dt;a.y+=a.dy*36*dt;clampGrass(a);const ks=SPINE_KIND[a.k];if(ks)setAnim(a.sid||a.k,Math.hypot(a.dx,a.dy)>0.05?ks.walk:ks.idle,true);});state.wild.forEach(w=>{if(!w.alive)return;if(Math.random()<0.015){w.dx=(Math.random()-0.5)*0.9;w.dy=(Math.random()-0.5)*0.9;}w.x+=w.dx*40*dt;w.y+=w.dy*40*dt;clampGrass(w);});state.guards.forEach((g,i)=>{g.x=p.x+Math.cos(state.time*0.8+i)*40-16;g.y=p.y+Math.sin(state.time*0.8+i)*24;clampGrass(g);});state.plots.forEach(pl=>{if(pl.crop&&pl.stage<CROPS[pl.crop].length-1){pl.grow+=dt;if(pl.grow>6){pl.grow=0;pl.stage+=1;}}});if(state.msgT>0)state.msgT-=dt;}
function drawActors(dt){if(!spineOk||!scene)return;scene.camera.position.x=state.cam.x+actors.width/2;scene.camera.position.y=-(state.cam.y+actors.height/2);scene.camera.viewportWidth=actors.width;scene.camera.viewportHeight=actors.height;scene.begin();const farmer=state.gender==='girl'?'girl':'boy';blit(farmer,state.player.x,state.player.y,state.player.facing,dt);state.animals.forEach(a=>blit(a.sid||a.k,a.x,a.y,a.dx<0?-1:1,dt));scene.end();}
function blit(id,x,y,facing,dt){const s=skeletons[id];if(!s)return;s.anim.update(dt);s.anim.apply(s.skeleton);s.skeleton.x=x;s.skeleton.y=-y;s.skeleton.scaleX=Math.abs(s.skeleton.scaleX||0.3)*(facing<0?-1:1);try{if(spine.Physics)s.skeleton.updateWorldTransform(spine.Physics.update);else s.skeleton.updateWorldTransform();}catch(e){try{s.skeleton.updateWorldTransform();}catch(e2){}}scene.drawSkeleton(s.skeleton,true);}
function hud(){document.getElementById('stats').innerHTML='PAWLY ESTATE FARM · Lv '+state.lv+' · '+Math.min(state.xp,100)+'/100 XP · '+state.pt+' PT<br>W/T/C/R '+state.inv.wheat+'/'+state.inv.tomato+'/'+state.inv.corn+'/'+state.inv.carrot+' · Wood '+state.inv.wood+' · Fish '+state.inv.fish+' · Meat '+state.inv.meat+' · Caught '+state.inv.caught+' · Guards '+state.guards.length+(state.msgT>0?'<br>'+state.msg:'');}
function setTools(){const box=document.getElementById('tools');box.innerHTML='';[['wheat','Wheat',0],['tomato','Tomato',0],['corn','Corn',0],['carrot','Carrot',0],['harvest','Harvest',0],['chop','Chop',0],['fish','Fish Lv1',1],['hunt','Hunt Lv5',5],['tame','Tame Lv20',20],['chickens','Chickens Lv10',10],['cattle','Cattle Lv15',15],['expand','Clear 80PT',1]].forEach(([id,label,lv])=>{const b=document.createElement('button');b.textContent=state.lv>=lv?label:label+' 🔒';if(state.tool===id)b.classList.add('on');b.onclick=()=>{if(state.lv<lv){say('Need level '+lv);return;}state.tool=id;setTools();};box.appendChild(b);});}
function addXp(n){state.xp+=n;while(state.xp>=100&&state.lv<99){const fee=state.lv<5?50:state.lv<15?100:state.lv<30?180:360;if(state.pt<fee){state.xp=100;say('Need '+fee+' PT to level');break;}state.pt-=fee;state.xp-=100;state.lv+=1;say('Level '+state.lv);setTools();}}
function worldPos(ev,el){const r=el.getBoundingClientRect();return{x:((ev.clientX-r.left)/r.width)*world.width+state.cam.x,y:((ev.clientY-r.top)/r.height)*world.height+state.cam.y};}
function hitWild(pos){return state.wild.find(w=>w.alive&&pos.x>=w.x&&pos.x<w.x+48&&pos.y>=w.y&&pos.y<w.y+40);}
function onTap(ev){if(state.screen!=='play')return;const pos=worldPos(ev.touches?ev.touches[0]:ev,world);const plot=state.plots.find(p=>pos.x>=p.x&&pos.x<p.x+50&&pos.y>=p.y&&pos.y<p.y+44);const tree=state.trees.find(t=>t.hp>0&&pos.x>=t.x&&pos.x<t.x+110&&pos.y>=t.y&&pos.y<t.y+150);const prey=hitWild(pos);if(state.tool==='fish'){if(!canUse('fish',1,100,'openedFish'))return;if(pos.x>880&&pos.y>300&&pos.y<460){state.inv.fish+=1;addXp(3);say('Caught a fish');}return;}if(state.tool==='hunt'){if(!canUse('hunt',5,150,'openedHunt'))return;if(prey){prey.alive=false;state.inv.meat+=1;state.inv.caught+=1;addXp(8);say('Hunted '+prey.k);}else say('Tap a fox / rabbit / wolf on the grass');return;}if(state.tool==='tame'){if(!canUse('tame',20,300,'openedTame'))return;if(state.inv.caught<1){say('Hunt first');return;}if(prey&&prey.alive){prey.alive=false;state.inv.caught-=1;state.guards.push({spr:prey.k+'.png',x:prey.x,y:prey.y});addXp(10);say(prey.k+' guards the farm');}else say('Tap a live wild animal');return;}if(state.tool==='chickens'){if(!canUse('live',10,200,'openedLive'))return;spawnStock('chicken',pos.x,pos.y);addXp(4);say('Added chickens');return;}if(state.tool==='cattle'){if(!canUse('cattle',15,250,'openedCattle'))return;spawnStock(Math.random()<0.5?'cow':'sheep',pos.x,pos.y);addXp(5);say('Added cattle');return;}if(state.tool==='chop'&&tree){tree.hp-=1;if(tree.hp<=0){state.inv.wood+=2;addXp(6);say('Tree down');}return;}if(plot){if(plot.locked){if(state.tool==='expand'&&state.pt>=80){state.pt-=80;plot.locked=false;addXp(2);}else say('Use Clear 80PT');return;}if(state.tool==='harvest'){const st=CROPS[plot.crop];if(plot.crop&&st&&plot.stage>=st.length-1){state.inv[plot.crop]+=1;addXp(4);plot.crop='';plot.stage=0;plot.grow=0;}return;}if(CROPS[state.tool]&&!plot.crop){plot.crop=state.tool;plot.stage=0;plot.grow=0;return;}}state.target=pos;}
function loop(ts){const dt=Math.min(0.05,(ts-(state.last||ts))/1000);state.last=ts;state.time+=dt;if(state.screen==='play'){updateLogic(dt);drawWorld();nightTint();drawActors(dt);hud();}requestAnimationFrame(loop);}
function fit(){world.width=actors.width=Math.min(1280,window.innerWidth);world.height=actors.height=Math.min(720,window.innerHeight);fitCam();}
window.addEventListener('resize',fit);window.addEventListener('keydown',e=>state.keys[e.key]=true);window.addEventListener('keyup',e=>state.keys[e.key]=false);world.addEventListener('click',onTap);world.addEventListener('touchstart',e=>{onTap(e);e.preventDefault();},{passive:false});
document.querySelectorAll('#select button').forEach(b=>{b.onclick=()=>{state.gender=b.dataset.g;document.getElementById('select').style.display='none';state.screen='play';setTools();};});
fit();makeWorld();Promise.all(PNG.map(loadPng)).then(()=>initSpine()).finally(()=>{const boot=document.getElementById('boot');if(boot)boot.style.display='none';requestAnimationFrame(loop);});
